<?php
/**
 * @category   ZendMonk
 * @package    ZendMonk_LoginRequired
 * @author     Carl Monk <@ZendMonk>
 *
 * @var	Mage_Customer_Block_Account_Forgotpassword $this
 */
?>
<?php if ($_messagesHtml = $this->getMessagesBlock()->getGroupedHtml()): ?>
	<div class="messages-container"><?php echo $_messagesHtml ?></div>
<?php endif; ?>
<div class="page-title">
    <h1><?php echo $this->__('Retrieve forgotten Password') ?></h1>
</div>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
<?php if ($this->isLoginPageDisabled() && ($_isRefererSet = $this->isRefererSet())): ?>
	<div class="no-display">
		<input type="hidden" value="<?php echo $this->getRefererValue(); ?>" name="referer">
	</div>
<?php endif; ?>
    <div class="fieldset">
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                </div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info'); ?>
        </ul>
    </div>
	<div class="buttons-set">
<?php if ($this->isLoginPageDisabled()): if ($_isRefererSet): ?>
		<a href="<?php echo $this->getRefererUrl(); ?>" title="<?php echo $this->__('Return to Previous Page') ?>" class="original-link m-increase"><?php echo $this->__('Return to Previous Page') ?></a>
<?php else: ?>
		<a href="<?php echo Mage::getUrl(); ?>" title="<?php echo $this->__('Return to Home Page') ?>" class="original-link m-increase"><?php echo $this->__('Return to Home Page') ?></a>
<?php endif; else: ?>
		<a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" title="<?php echo $this->__('Return to Customer Log In Page') ?>" class="original-link m-increase" rel="nofollow"><?php echo $this->__('Return to Customer Log In Page') ?></a>
<?php endif; ?>
		<div class="button-container">
			<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><?php echo $this->__('Submit') ?></span></button>
		</div>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
