<?php
/**
 * @category   ZendMonk
 * @package    ZendMonk_LoginRequired
 * @author     Carl Monk <@ZendMonk>
 *
 * @var	Mage_Page_Block_Html_Notices $this
 */
?>
<div id="site-notice-no-cookies" class="site-notice-container site-notice-container-js" style="display:none;">
    <div class="site-notice-outer">
        <div class="site-notice-inner">
        	<p><strong><?php echo $this->__('Please enable Cookies.'); ?></strong></p>
            <p><?php echo $this->__('You must have Cookies enabled in order to visit our Online Store.'); ?></p>
        </div>
    </div>
</div>
<?php
	$_helper = Mage::helper('zendmonk_loginrequired');
	$_customerHelper = Mage::helper('customer');
	$_forgotPasswordUrl = $_customerHelper->getForgotPasswordUrl();
	if ($_helper->isLoginPageDisabled()) {
		$_forgotPasswordUrl .= 'referer/'.base64_encode(Mage::helper('core/url')->getCurrentUrl()).'/';
	}
?>
<div id="site-notice-login-required" class="site-notice-container site-notice-container-js" style="display:none;">
    <div class="site-notice-outer">
        <div class="site-notice-inner">
<?php
	$_messagesBlock = $this->getMessagesBlock();
	$_messagesBlock->addMessages(Mage::getSingleton('customer/session')->getMessages(true));
	if ($_messageHtml = $_messagesBlock->getGroupedHtml()): ?>
			<div class="messages-container"><?php echo $_messageHtml; ?></div>
<?php endif; ?>
			<form action="<?php echo $_customerHelper->getLoginPostUrl(); ?>" method="post" id="login-form">
                <p><strong><?php echo $_helper->getPopupTitle(); ?></strong></p>
				<?php echo $_helper->getPopupInfoTop(); ?>
				<ul class="form-list">
					<li>
						<label for="email" class="required"><?php echo $this->__('Email Address') ?></label>
						<div class="input-box">
							<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
						</div>
					</li>
					<li>
						<label for="pass" class="required"><?php echo $this->__('Password') ?></label>
						<div class="input-box">
							<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
						</div>
					</li>
				</ul>
				<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
				<a href="<?php echo $_forgotPasswordUrl; ?>" title="<?php echo $this->__('Retrieve forgotten Password') ?>" class="original-link m-increase" rel="nofollow"><?php echo $this->__('Forgot Your Password?') ?></a>
				<div class="button-container">
					<button type="submit" class="button" title="<?php echo $_customerHelper->__('Log in') ?>" name="send" id="send2"><span><?php echo $_customerHelper->__('Log in') ?></span></button>
				</div>
				<?php echo $_helper->getPopupInfoBottom(); ?>
			</form>
		    <script type="text/javascript">
		    //<![CDATA[
		        var dataForm = new VarienForm('login-form', true);
		    //]]>
		    </script>
        </div>
    </div>
</div>
<?php
	if (!$_helper->removeCookieScripts()): ?>
<script type="text/javascript">
/* <![CDATA[ */
var CookieManager = new CookieManagerClass(new Date(new Date().getTime() + <?php echo Mage::helper('core/cookie')->getCookieRestrictionLifetime() ?> * 1000));
/* ]]> */
</script>
<?php endif; ?>
